(function(){
'use strict';
const D=window.ChapadaWaterfalls,C=window.ChapadaPackage,G=window.ExplorerGuides,e=C.esc;
let map,routeLayer,pointLayer,attractionLayer,baseLayer,openPanel,closePanel,prepareRequest,stage='transfer',baseId='flor-da-chapada',payment='A combinar',arrival='',flight='',flightConfirmed=false;
const picked=new Map();
function getSelectedLodge(){return C.stops().find(l=>l.id===baseId)||C.stops()[0];}
function pin(text,type){return L.divIcon({className:'regional-marker',html:`<span class="map-pin ${type}">${text}</span>`,iconSize:[40,40],iconAnchor:[20,20]});}
function marker(group,p,text,type,click){const m=L.marker([p.lat,p.lng],{icon:pin(text,type),title:p.nome}).addTo(group);m.on('click',click);m.bindTooltip(p.nome);return m;}
function label(l){return l.short||l.nome;}
function urlOrder(){const u=new URL(location.href);u.searchParams.set('ordem',C.order);history.replaceState(null,'',u);}
function refreshLabel(){document.getElementById('selected-lodge-label').textContent=`8 noites · R$ 20.000/casal · Base dos passeios: ${getSelectedLodge().short}`;}
function draw(){
routeLayer.clearLayers();pointLayer.clearLayers();baseLayer.clearLayers();
const colors=['#146da0','#b66b13','#6845a5','#315c37'];
C.legs().forEach((leg,i)=>{L.geoJSON({type:'LineString',coordinates:leg.coordinates},{style:{color:colors[i],weight:6-i,opacity:.85,dashArray:i===3?'8 6':null}}).addTo(routeLayer).bindTooltip(`${i+1} · Dia ${leg.day}: ${label(leg.from)} → ${label(leg.to)}`);});
marker(pointLayer,D.origem,'✈','airport-pin',()=>openPanel(`<h2>${e(D.origem.nome)}</h2><p>Encontro no dia 1 e retorno no dia 9. Horários combinados de acordo com os voos informados.</p><p>Passagens e deslocamentos até este aeroporto são responsabilidade do viajante.</p>`));
C.stops().forEach((l,i)=>marker(pointLayer,l,String(i+1),'lodge-pin',()=>openLodgeDetails(l)));
marker(baseLayer,getSelectedLodge(),'⌂','lodge-pin selected-lodge',()=>openLodgeDetails(getSelectedLodge()));refreshLabel();
}
function showLayers(){const transfer=stage==='transfer';[routeLayer,pointLayer].forEach(l=>{if(transfer)l.addTo(map);else map.removeLayer(l);});if(transfer){map.removeLayer(attractionLayer);map.removeLayer(baseLayer);}else{attractionLayer.addTo(map);baseLayer.addTo(map);}document.getElementById('chapada-transfer-button').setAttribute('aria-pressed',String(transfer));document.getElementById('chapada-attractions-button').setAttribute('aria-pressed',String(!transfer));const bounds=transfer?pointLayer.getBounds():attractionLayer.getBounds().extend([getSelectedLodge().lat,getSelectedLodge().lng]);if(bounds.isValid())map.fitBounds(bounds,{padding:[35,35]});}
function openLodgeDetails(l){openPanel(`<span class="eyebrow">HOSPEDAGEM · SEU CIRCUITO</span><div class="circuit-stage ${l.theme}"><h2>${e(l.headline)}</h2><p>${e(l.experience)}</p><div class="stage-meal">${e(l.meals)}</div></div>${C.lodgeHTML(l,true)}${l.id==='flor-da-chapada'?'<button id="use-base" class="action-button">Ver sugestões de passeios desde a Flor</button>':''}`);if(l.id==='flor-da-chapada')document.getElementById('use-base').onclick=showAttractions;}
function openTransferPlanner(){
const legs=C.legs();openPanel(`<div class="circuit-panel-cover"><span class="eyebrow">9 DIAS · 8 NOITES · UM CIRCUITO</span><h2>Parque, Cachoeiras<br>e Penhasco.</h2><p>Três jeitos de viver a Chapada. Você escolhe onde começa; nós cuidamos do caminho.</p><span class="circuit-price-tag">R$ 20.000,00 por casal</span></div>${C.stagesHTML()}<p class="circuit-route-caption">Do Aeroporto Marechal Rondon às três pousadas, com retorno ao aeroporto no dia 9. Todos os traslados do circuito estão incluídos.</p><details class="package-start"><summary>Por onde você quer começar?</summary><label for="map-order">Primeira pousada</label><select id="map-order"><option value="parque"${C.order==='parque'?' selected':''}>Pousada do Parque · 2 noites</option><option value="penhasco"${C.order==='penhasco'?' selected':''}>Penhasco · 1 noite</option></select>${C.stops().map((l,i)=>C.lodgeHTML(l,i===0)).join('')}<button id="confirm-order" class="action-button">Confirmar e ver percurso no mapa</button></details><ol class="package-legs">${legs.map((l,i)=>`<li><strong>${i+1} · Dia ${l.day}</strong><span>${e(label(l.from))} → ${e(label(l.to))}</span><a href="${C.directions(l.from,l.to)}" target="_blank" rel="noopener">Abrir trajeto rodoviário ↗</a></li>`).join('')}</ol><p class="small-note">Traçados de referência da base existente. A navegação atualizada está nos links de cada trecho. Horários de chegada e saída são combinados com a operação.</p><button id="see-route" class="action-button light">Visualizar mapa completo</button>`);
document.getElementById('confirm-order').onclick=()=>{C.setOrder(document.getElementById('map-order').value);baseId='flor-da-chapada';urlOrder();draw();stage='transfer';showLayers();openTransferPlanner();closePanel();};document.getElementById('see-route').onclick=closePanel;
}
function km(a,b){const r=x=>x*Math.PI/180,dlat=r(b.lat-a.lat),dlng=r(b.lng-a.lng),v=Math.sin(dlat/2)**2+Math.cos(r(a.lat))*Math.cos(r(b.lat))*Math.sin(dlng/2)**2;return 6371*2*Math.atan2(Math.sqrt(v),Math.sqrt(1-v));}
function attractionHTML(p){const l=getSelectedLodge();return `<span class="eyebrow">SUGESTÃO PARA O SEU ROTEIRO</span><h2>${e(p.nome)}</h2><p>${e(p.descricao)}</p><p>Saída de <strong>${e(l.short)}</strong> · dias ${l.start} a ${l.end}.</p><p>${km(l,p).toFixed(1).replace('.',',')} km em linha reta — não é distância rodoviária.</p><a class="action-button" href="${C.directions(l,p)}" target="_blank" rel="noopener">Traçar rota desde ${e(l.short)} ↗</a><p>Guia, carro, ingressos do roteiro combinado e três almoços estão incluídos nos três dias de passeios. ${e(C.conditions)} Marcar interesse não confirma a visita a todas as atrações.</p><button id="pick-attraction" class="action-button light">${picked.has(p.id)?'Remover do meu interesse':'Tenho interesse neste passeio'}</button><button id="back-attractions" class="action-button light">Voltar às atrações</button>`;}
function showAttraction(p){openPanel(attractionHTML(p));document.getElementById('pick-attraction').onclick=()=>{if(picked.has(p.id))picked.delete(p.id);else picked.set(p.id,baseId);showAttraction(p);};document.getElementById('back-attractions').onclick=showAttractions;}
function showAttractions(){stage='attractions';showLayers();const base=getSelectedLodge(),sorted=D.atracoes.slice().sort((a,b)=>km(base,a)-km(base,b));openPanel(`<span class="eyebrow">ATRAÇÕES · FLOR DA CHAPADA</span><h2>Passeios no seu ritmo</h2><div class="circuit-base"><strong>Flor da Chapada · sua base</strong><span>Etapa 2 · dias ${base.start} a ${base.end}</span></div><p>${e(C.conditions)}</p><p>Guia, carro, ingressos e três almoços incluídos nos três dias de passeio. A lista é um conjunto de sugestões, não uma promessa de visitar todas as atrações.</p><p class="small-note">Ordenadas pela proximidade em linha reta da Flor da Chapada.</p><ol class="package-attractions">${sorted.map(p=>`<li><button class="attraction-item" data-place="${p.id}"><b>${e(p.nome)}</b><span>${e(p.tipo)} · ${km(base,p).toFixed(1).replace('.',',')} km${picked.has(p.id)?' · Interesse registrado':''}</span></button></li>`).join('')}</ol><button id="view-attraction-map" class="action-button">Ver atrações no mapa</button>`);document.querySelectorAll('[data-place]').forEach(b=>b.onclick=()=>showAttraction(D.atracoes.find(p=>p.id===b.dataset.place)));document.getElementById('view-attraction-map').onclick=closePanel;}
function flightReady(){return Boolean(arrival && flight.trim() && flightConfirmed);}
function requestLines(){return [...C.inclusions(),'Traslados incluídos: '+[D.origem,...C.stops(),D.origem].map(label).join(' → '),'Chegada prevista: '+(arrival||'A combinar')+' (sujeita a ajuste após confirmação do voo).','Número do voo de chegada: '+(flight.trim()||'Ainda não informado'),'Confirmação do voo pelo cliente: '+(flightReady()?'Informada pelo cliente; aguardando conferência pelo Bento Pantanal.':'Pendente — pedido preliminar, sem assinatura ou pagamento.'),'Preferência de pagamento: '+payment,'Se optar por criptomoeda, moeda, rede e cotação serão combinadas no atendimento.',...Array.from(picked,([id])=>`Sugestão de interesse: ${D.atracoes.find(p=>p.id===id).nome} — saída da Flor da Chapada.`)];}
function updateFlightStatus(){const ready=flightReady();document.getElementById('flight-status').textContent=ready?'Você informou o voo confirmado. Vamos conferir os dados com você antes de seguir para a assinatura do contrato.':'Ainda sem voo confirmado? Você pode planejar a viagem agora. A assinatura do contrato e a etapa de pagamento ficam para depois da confirmação do voo.';document.getElementById('request-package').textContent=ready?'Enviar dados para preparar o contrato':'Enviar meu planejamento inicial';}
function paymentPanel(){const guide=G.getSelected();openPanel(`<span class="eyebrow">SUA VIAGEM, PASSO A PASSO</span><h2>Escolha seu guia</h2><button id="choose-package-guide" class="action-button">${guide?'Trocar guia':'Escolher guia'}</button><p>${guide?e(window.PantanalGuides.displayName(guide)):'Conhecimento local para aproveitar cada dia. O acompanhamento do guia nos três dias de passeios está incluído.'}</p>${guide?`<a class="guide-profile-link" href="${e(window.PantanalGuides.guidePath(guide.slug))}" target="_blank" rel="noopener">Ver perfil e contato do guia ↗</a>`:''}<div class="circuit-total"><span>O CIRCUITO PARA VOCÊS DOIS</span><strong>R$ 20.000,00</strong><p>9 dias / 8 noites · hospedagens, traslados e três dias de passeios com guia, carro, ingressos e três almoços.</p></div><label for="package-arrival">Data prevista de chegada</label><input id="package-arrival" type="date" value="${e(arrival)}"><p class="small-note">Essa data pode ser alterada quando você confirmar seu voo. A compra da passagem é por sua conta.</p><h3>Pagamentos aceitos</h3><div class="payment-methods"><span>Dinheiro</span><span>Pix</span><span>Transferência</span><span>Cartão</span><span>Criptomoeda</span></div><label for="package-payment">Sua preferência</label><select id="package-payment">${['A combinar','Dinheiro','Pix','Transferência','Cartão','Criptomoeda'].map(x=>`<option value="${x}"${payment===x?' selected':''}>${x}</option>`).join('')}</select><p class="small-note">Condições combinadas no atendimento. Em criptomoeda, confirmamos moeda, rede e cotação antes da transferência.</p><div class="flight-contract"><h3>Primeiro o voo. Depois o contrato.</h3><ol><li>Você providencia sua passagem e confirma o número do voo de chegada a Várzea Grande.</li><li>Conferimos os dados da viagem e seguimos para a assinatura do contrato.</li><li>O pagamento é combinado nessa etapa. Nenhum pagamento é necessário antes da confirmação do voo e da etapa de assinatura.</li></ol><details><summary>Já tenho meu voo de chegada</summary><label for="arrival-flight">Número do voo</label><input id="arrival-flight" maxlength="30" autocomplete="off" placeholder="Ex.: AB 1234" value="${e(flight)}"><label class="flight-check"><input id="flight-confirmed" type="checkbox"${flightConfirmed?' checked':''}> Confirmo que este voo está confirmado pela companhia aérea.</label></details></div><p id="flight-status" class="flight-status" role="status"></p><button id="request-package" class="action-button">Enviar meu planejamento inicial</button><p class="small-note">O botão prepara uma mensagem para o Bento Pantanal. Reserva e guia dependem de disponibilidade. Esta página não assina contratos nem realiza cobranças.</p>`);
document.getElementById('package-payment').onchange=ev=>payment=ev.target.value;document.getElementById('package-arrival').onchange=ev=>{arrival=ev.target.value;flightConfirmed=false;document.getElementById('flight-confirmed').checked=false;updateFlightStatus();};document.getElementById('arrival-flight').oninput=ev=>{flight=ev.target.value;flightConfirmed=false;document.getElementById('flight-confirmed').checked=false;updateFlightStatus();};document.getElementById('flight-confirmed').onchange=ev=>{flightConfirmed=ev.target.checked;updateFlightStatus();};document.getElementById('choose-package-guide').onclick=()=>G.openPicker(paymentPanel);document.getElementById('request-package').onclick=prepareRequest;updateFlightStatus();}
function init(opts){if(!window.L)throw Error('Mapa indisponível');({openPanel,closePanel,prepareRequest}=opts);map=L.map('map');L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; OpenStreetMap · rotas de referência OSRM'}).addTo(map);routeLayer=L.featureGroup();pointLayer=L.featureGroup();attractionLayer=L.featureGroup();baseLayer=L.featureGroup();D.atracoes.forEach((p,i)=>marker(attractionLayer,p,String(i+1),'attraction-pin',()=>showAttraction(p)));draw();showLayers();urlOrder();document.getElementById('chapada-transfer-button').onclick=()=>{stage='transfer';showLayers();openTransferPlanner();};document.getElementById('chapada-attractions-button').onclick=showAttractions;document.getElementById('chapada-guide-button').onclick=paymentPanel;document.getElementById('chapada-plan-button').onclick=openTransferPlanner;setTimeout(()=>{map.invalidateSize();openTransferPlanner();},0);}
window.ChapadaExplorer=Object.freeze({init,getDays:()=>9,getSelectedLodge,isReady:()=>true,openTransferPlanner,openLodgeDetails,requestLines,attractionCount:()=>D.atracoes.length});
})();
