(function(){
'use strict';
const D=window.ChapadaWaterfalls,C=window.ChapadaPackage,G=window.ExplorerGuides,e=C.esc;
let map,routeLayer,pointLayer,attractionLayer,baseLayer,openPanel,closePanel,prepareRequest,stage='transfer',baseId=C.stops()[0].id,payment='A combinar',arrival='';
const picked=new Map();
function getSelectedLodge(){return C.stops().find(l=>l.id===baseId)||C.stops()[0];}
function pin(text,type){return L.divIcon({className:'regional-marker',html:`<span class="map-pin ${type}">${text}</span>`,iconSize:[40,40],iconAnchor:[20,20]});}
function marker(group,p,text,type,click){const m=L.marker([p.lat,p.lng],{icon:pin(text,type),title:p.nome}).addTo(group);m.on('click',click);m.bindTooltip(p.nome);return m;}
function label(l){return l.short||l.nome;}
function urlOrder(){const u=new URL(location.href);u.searchParams.set('ordem',C.order);history.replaceState(null,'',u);}
function refreshLabel(){document.getElementById('selected-lodge-label').textContent=`8 noites · R$ 20.000/casal · Base dos passeios: ${getSelectedLodge().short}`;}
function draw(){
routeLayer.clearLayers();pointLayer.clearLayers();baseLayer.clearLayers();
const colors=['#146da0','#b66b13','#6845a5','#315c37'];
C.legs().forEach((leg,i)=>{L.geoJSON({type:'LineString',coordinates:leg.coordinates},{style:{color:colors[i],weight:6-i,opacity:.85,dashArray:i===3?'8 6':null}}).addTo(routeLayer).bindTooltip(`${i+1} · Dia ${leg.day}: ${label(leg.from)} → ${label(leg.to)}`);});
marker(pointLayer,D.origem,'✈','airport-pin',()=>openPanel(`<h2>${e(D.origem.nome)}</h2><p>Encontro no dia 1 e retorno no dia 9. Horários combinados de acordo com os voos informados.</p><p>Passagens e deslocamentos até este aeroporto são responsabilidade do viajante.</p>`));
C.stops().forEach((l,i)=>marker(pointLayer,l,String(i+1),'lodge-pin',()=>openLodgeDetails(l)));
marker(baseLayer,getSelectedLodge(),'⌂','lodge-pin selected-lodge',()=>openLodgeDetails(getSelectedLodge()));refreshLabel();
}
function showLayers(){const transfer=stage==='transfer';[routeLayer,pointLayer].forEach(l=>{if(transfer)l.addTo(map);else map.removeLayer(l);});if(transfer){map.removeLayer(attractionLayer);map.removeLayer(baseLayer);}else{attractionLayer.addTo(map);baseLayer.addTo(map);}document.getElementById('chapada-transfer-button').setAttribute('aria-pressed',String(transfer));document.getElementById('chapada-attractions-button').setAttribute('aria-pressed',String(!transfer));const bounds=transfer?pointLayer.getBounds():attractionLayer.getBounds().extend([getSelectedLodge().lat,getSelectedLodge().lng]);if(bounds.isValid())map.fitBounds(bounds,{padding:[35,35]});}
function openLodgeDetails(l){openPanel(`<span class="eyebrow">HOSPEDAGEM · CHAPADA 20K</span>${C.lodgeHTML(l,true)}<button id="use-base" class="action-button">Ver atrações a partir desta pousada</button>`);document.getElementById('use-base').onclick=()=>{baseId=l.id;draw();showAttractions();};}
function openTransferPlanner(){
const legs=C.legs();openPanel(`<span class="eyebrow">CHAPADA 20K · 9 DIAS / 8 NOITES</span><h2>Seu traslado completo</h2><p>Aeroporto → três pousadas → aeroporto. Hospedagem e traslados incluídos nos R$ 20.000 por casal.</p><details class="package-start"><summary>Por onde você quer começar?</summary><label for="map-order">Primeira pousada</label><select id="map-order"><option value="parque"${C.order==='parque'?' selected':''}>Pousada do Parque · 2 noites</option><option value="penhasco"${C.order==='penhasco'?' selected':''}>Penhasco · 1 noite</option></select>${C.stops().map((l,i)=>C.lodgeHTML(l,i===0)).join('')}<button id="confirm-order" class="action-button">Confirmar e ver percurso no mapa</button></details><ol class="package-legs">${legs.map((l,i)=>`<li><strong>${i+1} · Dia ${l.day}</strong><span>${e(label(l.from))} → ${e(label(l.to))}</span><a href="${C.directions(l.from,l.to)}" target="_blank" rel="noopener">Abrir trajeto rodoviário ↗</a></li>`).join('')}</ol><p class="small-note">Traçados de referência da base existente. A navegação atualizada está nos links de cada trecho. Horários de chegada e saída são combinados com a operação.</p><button id="see-route" class="action-button light">Visualizar mapa completo</button>`);
document.getElementById('confirm-order').onclick=()=>{C.setOrder(document.getElementById('map-order').value);baseId=C.stops()[0].id;urlOrder();draw();stage='transfer';showLayers();openTransferPlanner();closePanel();};document.getElementById('see-route').onclick=closePanel;
}
function km(a,b){const r=x=>x*Math.PI/180,dlat=r(b.lat-a.lat),dlng=r(b.lng-a.lng),v=Math.sin(dlat/2)**2+Math.cos(r(a.lat))*Math.cos(r(b.lat))*Math.sin(dlng/2)**2;return 6371*2*Math.atan2(Math.sqrt(v),Math.sqrt(1-v));}
function attractionHTML(p){const l=getSelectedLodge();return `<span class="eyebrow">PASSEIO CONTRATADO À PARTE</span><h2>${e(p.nome)}</h2><p>${e(p.descricao)}</p><p>Saída de <strong>${e(l.short)}</strong> · dias ${l.start} a ${l.end}.</p><p>${km(l,p).toFixed(1).replace('.',',')} km em linha reta — não é distância rodoviária.</p><a class="action-button" href="${C.directions(l,p)}" target="_blank" rel="noopener">Traçar rota desde ${e(l.short)} ↗</a><p>Transporte, guia, ingresso e preço deste passeio são combinados diretamente com o guia. A seleção registra seu interesse, sem confirmar uma reserva.</p><button id="pick-attraction" class="action-button light">${picked.has(p.id)?'Remover do meu interesse':'Tenho interesse neste passeio'}</button><button id="back-attractions" class="action-button light">Voltar às atrações</button>`;}
function showAttraction(p){openPanel(attractionHTML(p));document.getElementById('pick-attraction').onclick=()=>{if(picked.has(p.id))picked.delete(p.id);else picked.set(p.id,baseId);showAttraction(p);};document.getElementById('back-attractions').onclick=showAttractions;}
function showAttractions(){stage='attractions';showLayers();const base=getSelectedLodge(),sorted=D.atracoes.slice().sort((a,b)=>km(base,a)-km(base,b));openPanel(`<span class="eyebrow">ATRAÇÕES · ESCOLHA SUA BASE</span><h2>Passeios no seu ritmo</h2><label for="attraction-base">De qual pousada você vai sair?</label><select id="attraction-base">${C.stops().map(l=>`<option value="${l.id}"${l.id===baseId?' selected':''}>${e(l.short)} · dias ${l.start} a ${l.end}</option>`).join('')}</select><p>Ordenadas pela proximidade em linha reta da base escolhida. Transporte e valores são definidos com o guia.</p><ol class="package-attractions">${sorted.map(p=>`<li><button class="attraction-item" data-place="${p.id}"><b>${e(p.nome)}</b><span>${e(p.tipo)} · ${km(base,p).toFixed(1).replace('.',',')} km${picked.has(p.id)?' · Interesse registrado':''}</span></button></li>`).join('')}</ol><button id="view-attraction-map" class="action-button">Ver atrações no mapa</button>`);document.getElementById('attraction-base').onchange=ev=>{baseId=ev.target.value;draw();showAttractions();};document.querySelectorAll('[data-place]').forEach(b=>b.onclick=()=>showAttraction(D.atracoes.find(p=>p.id===b.dataset.place)));document.getElementById('view-attraction-map').onclick=closePanel;}
function requestLines(){return ['Pacote: Chapada 20K — R$ 20.000 por casal (2 pessoas).','Duração: 9 dias / 8 noites.',...C.stops().map(l=>`${l.short}: ${l.nights} noites — dias ${l.start} a ${l.end}.`),'Traslados incluídos: '+[D.origem,...C.stops(),D.origem].map(label).join(' → '),'Chegada prevista: '+(arrival||'A combinar'),'Preferência de pagamento do pacote: '+payment,'Pagamento em criptomoeda: moeda, rede e cotação confirmadas pelo Bento Pantanal antes de qualquer transferência.','Inclui hospedagem, traslados aeroporto/pousadas, transferências entre pousadas e contato do guia.','Passeios, transporte às atrações, acompanhamento e ingressos são contratados e pagos diretamente ao guia.','Passagens aéreas não incluídas. Categoria, refeições e acesso ao lazer: confirmar na proposta.',...Array.from(picked,([id,base])=>`Interesse: ${D.atracoes.find(p=>p.id===id).nome} — saída de ${C.stops().find(l=>l.id===base).short}.`)];}
function paymentPanel(){const guide=G.getSelected();openPanel(`<span class="eyebrow">GUIAS E PAGAMENTO</span><h2>R$ 20.000 por casal</h2><p>O pagamento do pacote é combinado com o Bento Pantanal. Passeios e seus custos são acertados diretamente com o guia.</p><h3>Seu guia</h3><p>${guide?e(window.PantanalGuides.displayName(guide)):'Escolha um guia VIP da rede para combinar seus passeios.'}</p>${guide?`<a class="action-button light" href="${e(window.PantanalGuides.guidePath(guide.slug))}" target="_blank" rel="noopener">Ver perfil e contato do guia ↗</a>`:''}<button id="choose-package-guide" class="action-button light">${guide?'Trocar guia':'Escolher guia'}</button><label for="package-arrival">Chegada prevista ao aeroporto</label><input id="package-arrival" type="date" value="${e(arrival)}"><label for="package-payment">Como prefere pagar o pacote?</label><select id="package-payment"><option${payment==='A combinar'?' selected':''}>A combinar</option><option${payment==='Criptomoeda'?' selected':''}>Criptomoeda</option></select><p class="small-note">Se escolher criptomoeda, combinaremos moeda, rede, cotação e dados para recebimento. Esta página não realiza cobrança nem confirma pagamento.</p><button id="request-package" class="action-button">Solicitar reserva e combinar pagamento</button><p class="small-note">Reserva e guia sujeitos à confirmação de disponibilidade. O pedido é preparado para envio; nenhuma mensagem é enviada automaticamente.</p>`);
document.getElementById('package-payment').onchange=ev=>payment=ev.target.value;document.getElementById('package-arrival').onchange=ev=>arrival=ev.target.value;document.getElementById('choose-package-guide').onclick=()=>G.openPicker(paymentPanel);document.getElementById('request-package').onclick=prepareRequest;}
function init(opts){if(!window.L)throw Error('Mapa indisponível');({openPanel,closePanel,prepareRequest}=opts);map=L.map('map');L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; OpenStreetMap · rotas de referência OSRM'}).addTo(map);routeLayer=L.featureGroup();pointLayer=L.featureGroup();attractionLayer=L.featureGroup();baseLayer=L.featureGroup();D.atracoes.forEach((p,i)=>marker(attractionLayer,p,String(i+1),'attraction-pin',()=>showAttraction(p)));draw();showLayers();urlOrder();document.getElementById('chapada-transfer-button').onclick=()=>{stage='transfer';showLayers();openTransferPlanner();};document.getElementById('chapada-attractions-button').onclick=showAttractions;document.getElementById('chapada-guide-button').onclick=paymentPanel;document.getElementById('chapada-plan-button').onclick=openTransferPlanner;setTimeout(()=>{map.invalidateSize();openTransferPlanner();},0);}
window.ChapadaExplorer=Object.freeze({init,getDays:()=>9,getSelectedLodge,isReady:()=>true,openTransferPlanner,openLodgeDetails,requestLines,attractionCount:()=>D.atracoes.length});
})();
